# Generated by Django 5.2.7 on 2025-11-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaldocumentversion',
            old_name='content',
            new_name='content_snapshot',
        ),
        migrations.CreateModel(
            name='LegalDocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='django_legal.legaldocument')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
