# Generated by Django 5.2.7 on 2025-11-22 00:00

from django.db import migrations, models


def dedupe_acceptances(apps, schema_editor):
    """
    Remove duplicate acceptances per (user, version) before adding a constraint.

    Keeps the earliest acceptance and deletes the rest.
    """
    Acceptance = apps.get_model("django_legal", "LegalDocumentAcceptance")

    duplicates = (
        Acceptance.objects.values("user_id", "version_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        qs = (
            Acceptance.objects.filter(
                user_id=dup["user_id"],
                version_id=dup["version_id"],
            )
            .order_by("accepted_at", "id")
            .values_list("id", flat=True)
        )
        ids = list(qs)
        if len(ids) > 1:
            # Keep the first, delete the rest.
            Acceptance.objects.filter(id__in=ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_legal", "0002_rename_content_legaldocumentversion_content_snapshot_and_more"),
    ]

    operations = [
        migrations.RunPython(dedupe_acceptances, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="legaldocumentacceptance",
            constraint=models.UniqueConstraint(
                fields=("user", "version"),
                name="unique_user_version_acceptance",
            ),
        ),
    ]
